{{- if and .Values.gateway.enabled .Values.gateway.oidc.enabled .Values.gateway.oidc.clientSecret (not .Values.gateway.oidc.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "porthole.oidcSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "porthole.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.gateway.oidc.clientSecret | quote }}
{{- end }}
