{{- if and .Values.gateway.enabled .Values.gateway.oidc.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "porthole.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "porthole.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "porthole.fullname" . }}
  oidc:
    provider:
      issuer: {{ .Values.gateway.oidc.issuer | quote }}
    clientID: {{ .Values.gateway.oidc.clientID | quote }}
    clientSecret:
      name: {{ include "porthole.oidcSecretName" . }}
    redirectURL: "https://{{ .Values.gateway.hostname }}/oauth2/callback"
    logoutPath: "/logout"
    scopes:
      {{- range .Values.gateway.oidc.scopes }}
      - {{ . | quote }}
      {{- end }}
    forwardAccessToken: {{ .Values.gateway.oidc.forwardAccessToken }}
{{- end }}
